POST https://db-med-supply.herokuapp.com/items/add
content-type: application/json

{
  "name": "item1",
  "category": "category1",
  "quantity": 1,
  "price": 11,
  "brand": "branded"
}


### Approve existing item
PATCH http://localhost:3000/items/2
content-Type:  application/json

{
  "approved": true
}


### Get existing item
GET http://localhost:3000/items?brand=branded


### Get All existing item
GET http://localhost:3000/items/all


### create new item
POST http://localhost:3000/items/add
content-type: application/json

{
  "name": "item2",
  "category": "category1",
  "quantity": 1,
  "price": 11,
  "brand": "branded",
  "imageUrl": "test"
}