POST http://localhost:3000/items/add
content-type: application/json

{
  "name": "item5",
  "category": "category5",
  "quantity": 5,
  "price": 123
}


### Approve existing item
PATCH http://localhost:3000/items/5
content-Type:  application/json

{
  "approved": true
}


### Get existing item
GET http://localhost:3000/items?name=steth
